// Starter list of ~70 courses to seed the shared course directory with.
// This is a generic, well-known-course starter list — replace it with your
// actual friend group's course list before running the seed script for real.

export interface SeedCourse {
  name: string;
  city: string;
  state: string;
  publicOrPrivate: "public" | "private";
}

export const courses: SeedCourse[] = [
  { name: "Pebble Beach Golf Links", city: "Pebble Beach", state: "CA", publicOrPrivate: "public" },
  { name: "Spyglass Hill Golf Course", city: "Pebble Beach", state: "CA", publicOrPrivate: "public" },
  { name: "Torrey Pines Golf Course (South)", city: "La Jolla", state: "CA", publicOrPrivate: "public" },
  { name: "Torrey Pines Golf Course (North)", city: "La Jolla", state: "CA", publicOrPrivate: "public" },
  { name: "Bethpage Black", city: "Farmingdale", state: "NY", publicOrPrivate: "public" },
  { name: "Bethpage Red", city: "Farmingdale", state: "NY", publicOrPrivate: "public" },
  { name: "Chambers Bay", city: "University Place", state: "WA", publicOrPrivate: "public" },
  { name: "Whistling Straits (Straits Course)", city: "Kohler", state: "WI", publicOrPrivate: "public" },
  { name: "Blackwolf Run (River Course)", city: "Kohler", state: "WI", publicOrPrivate: "public" },
  { name: "Erin Hills", city: "Erin", state: "WI", publicOrPrivate: "public" },
  { name: "TPC Sawgrass (Stadium Course)", city: "Ponte Vedra Beach", state: "FL", publicOrPrivate: "public" },
  { name: "Streamsong Red", city: "Bowling Green", state: "FL", publicOrPrivate: "public" },
  { name: "Streamsong Blue", city: "Bowling Green", state: "FL", publicOrPrivate: "public" },
  { name: "Streamsong Black", city: "Bowling Green", state: "FL", publicOrPrivate: "public" },
  { name: "World Woods Golf Club (Pine Barrens)", city: "Brooksville", state: "FL", publicOrPrivate: "public" },
  { name: "Bandon Dunes", city: "Bandon", state: "OR", publicOrPrivate: "public" },
  { name: "Pacific Dunes", city: "Bandon", state: "OR", publicOrPrivate: "public" },
  { name: "Bandon Trails", city: "Bandon", state: "OR", publicOrPrivate: "public" },
  { name: "Old Macdonald", city: "Bandon", state: "OR", publicOrPrivate: "public" },
  { name: "Pinehurst No. 2", city: "Pinehurst", state: "NC", publicOrPrivate: "public" },
  { name: "Pinehurst No. 4", city: "Pinehurst", state: "NC", publicOrPrivate: "public" },
  { name: "Tobacco Road Golf Club", city: "Sanford", state: "NC", publicOrPrivate: "public" },
  { name: "Kiawah Island Golf Resort (Ocean Course)", city: "Kiawah Island", state: "SC", publicOrPrivate: "public" },
  { name: "Harbour Town Golf Links", city: "Hilton Head Island", state: "SC", publicOrPrivate: "public" },
  { name: "Congaree Golf Club", city: "Ridgeland", state: "SC", publicOrPrivate: "private" },
  { name: "Kapalua Resort (Plantation Course)", city: "Lahaina", state: "HI", publicOrPrivate: "public" },
  { name: "Wailea Golf Club (Gold Course)", city: "Wailea", state: "HI", publicOrPrivate: "public" },
  { name: "Waikoloa Beach Resort (Beach Course)", city: "Waikoloa", state: "HI", publicOrPrivate: "public" },
  { name: "TPC Scottsdale (Stadium Course)", city: "Scottsdale", state: "AZ", publicOrPrivate: "public" },
  { name: "We-Ko-Pa Golf Club (Saguaro)", city: "Fort McDowell", state: "AZ", publicOrPrivate: "public" },
  { name: "Troon North Golf Club (Monument)", city: "Scottsdale", state: "AZ", publicOrPrivate: "public" },
  { name: "Sand Hollow Resort (Championship Course)", city: "Hurricane", state: "UT", publicOrPrivate: "public" },
  { name: "Coeur d'Alene Resort Golf Course", city: "Coeur d'Alene", state: "ID", publicOrPrivate: "public" },
  { name: "Sand Valley Golf Resort", city: "Nekoosa", state: "WI", publicOrPrivate: "public" },
  { name: "Mammoth Dunes", city: "Nekoosa", state: "WI", publicOrPrivate: "public" },
  { name: "Arcadia Bluffs (Bluffs Course)", city: "Arcadia", state: "MI", publicOrPrivate: "public" },
  { name: "Forest Dunes Golf Club", city: "Roscommon", state: "MI", publicOrPrivate: "public" },
  { name: "The Loop at Forest Dunes", city: "Roscommon", state: "MI", publicOrPrivate: "public" },
  { name: "Shanty Creek Resort (The Legend)", city: "Bellaire", state: "MI", publicOrPrivate: "public" },
  { name: "French Lick Resort (Pete Dye Course)", city: "French Lick", state: "IN", publicOrPrivate: "public" },
  { name: "Cog Hill Golf & Country Club (No. 4 Dubsdread)", city: "Lemont", state: "IL", publicOrPrivate: "public" },
  { name: "Medinah Country Club (Course No. 3)", city: "Medinah", state: "IL", publicOrPrivate: "private" },
  { name: "Prairie Dunes Country Club", city: "Hutchinson", state: "KS", publicOrPrivate: "private" },
  { name: "Sand Creek Station", city: "Newton", state: "KS", publicOrPrivate: "public" },
  { name: "Colorado Golf Club", city: "Parker", state: "CO", publicOrPrivate: "private" },
  { name: "The Broadmoor (East Course)", city: "Colorado Springs", state: "CO", publicOrPrivate: "public" },
  { name: "Ballyneal Golf Club", city: "Holyoke", state: "CO", publicOrPrivate: "private" },
  { name: "Omni Barton Creek (Fazio Canyons)", city: "Austin", state: "TX", publicOrPrivate: "public" },
  { name: "Whispering Pines Golf Club", city: "Trinity", state: "TX", publicOrPrivate: "private" },
  { name: "Cowboys Golf Club", city: "Grapevine", state: "TX", publicOrPrivate: "public" },
  { name: "TPC San Antonio (Oaks Course)", city: "San Antonio", state: "TX", publicOrPrivate: "public" },
  { name: "Southern Hills Country Club", city: "Tulsa", state: "OK", publicOrPrivate: "private" },
  { name: "Karsten Creek Golf Club", city: "Stillwater", state: "OK", publicOrPrivate: "private" },
  { name: "Shadow Creek Golf Course", city: "North Las Vegas", state: "NV", publicOrPrivate: "public" },
  { name: "Cascata Golf Course", city: "Boulder City", state: "NV", publicOrPrivate: "public" },
  { name: "Wynn Golf Club", city: "Las Vegas", state: "NV", publicOrPrivate: "public" },
  { name: "Winged Foot Golf Club (West Course)", city: "Mamaroneck", state: "NY", publicOrPrivate: "private" },
  { name: "Shinnecock Hills Golf Club", city: "Southampton", state: "NY", publicOrPrivate: "private" },
  { name: "Bethpage Green", city: "Farmingdale", state: "NY", publicOrPrivate: "public" },
  { name: "Yale Golf Course", city: "New Haven", state: "CT", publicOrPrivate: "public" },
  { name: "Merion Golf Club (East Course)", city: "Ardmore", state: "PA", publicOrPrivate: "private" },
  { name: "Oakmont Country Club", city: "Oakmont", state: "PA", publicOrPrivate: "private" },
  { name: "Congressional Country Club (Blue Course)", city: "Bethesda", state: "MD", publicOrPrivate: "private" },
  { name: "Caves Valley Golf Club", city: "Owings Mills", state: "MD", publicOrPrivate: "private" },
  { name: "Sweetens Cove Golf Club", city: "South Pittsburg", state: "TN", publicOrPrivate: "public" },
  { name: "The Honors Course", city: "Ooltewah", state: "TN", publicOrPrivate: "private" },
  { name: "Chattanooga Golf & Country Club", city: "Chattanooga", state: "TN", publicOrPrivate: "private" },
  { name: "East Lake Golf Club", city: "Atlanta", state: "GA", publicOrPrivate: "private" },
  { name: "Reynolds Lake Oconee (Great Waters)", city: "Greensboro", state: "GA", publicOrPrivate: "public" },
  { name: "Sea Island Golf Club (Seaside Course)", city: "St. Simons Island", state: "GA", publicOrPrivate: "public" },
  { name: "Old Waverly Golf Club", city: "West Point", state: "MS", publicOrPrivate: "private" },
  { name: "Fallen Oak", city: "Saucier", state: "MS", publicOrPrivate: "public" },
  { name: "Grand National (Lake Course)", city: "Opelika", state: "AL", publicOrPrivate: "public" },
  { name: "Ross Bridge", city: "Hoover", state: "AL", publicOrPrivate: "public" },
  { name: "Diamondback Golf Club", city: "Haymarket", state: "VA", publicOrPrivate: "public" },
  { name: "Kingsmill Resort (River Course)", city: "Williamsburg", state: "VA", publicOrPrivate: "public" },
  { name: "Old Chatham Golf Club", city: "Durham", state: "NC", publicOrPrivate: "private" },
  { name: "Sedgefield Country Club", city: "Greensboro", state: "NC", publicOrPrivate: "private" },
  { name: "Wade Hampton Golf Club", city: "Cashiers", state: "NC", publicOrPrivate: "private" },
];
